# docker-compose.yml
services:
  web:
    build: .
    command: >
      bash -c "python /code/core/manage.py makemigrations &&
               python /code/core/manage.py migrate &&
               python /code/core/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code 
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - DB_NAME=mydatabase
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - DB_HOST=db
      - DB_PORT=5432
     networks:
      -mynetwork

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
       - POSTGRES_DB=mydatabase  
       - POSTGRES_USER=myuser    
       - POSTGRES_PASSWORD=mypassword  
    ports:
       - "5433:5432"    
    networks:
       -mynetwork   

volumes:
  postgres_data:

networks:
  mynetwork:  
  