# Generated by Django 5.0.7 on 2024-07-20 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_rename_staff_id_course_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='staff',
        ),
    ]
