# Generated by Django 5.0.7 on 2024-07-20 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_remove_course_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='course',
        ),
        migrations.RemoveField(
            model_name='students',
            name='grade',
        ),
        migrations.AddField(
            model_name='staffs',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student.course'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('grade', models.CharField(max_length=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.course')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.students')),
            ],
        ),
    ]
