# Generated by Django 5.0.7 on 2024-07-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_remove_staffs_address_remove_students_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='gender',
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(default='Male', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffs',
            name='salary',
            field=models.CharField(default='15000', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='guardian',
            field=models.CharField(default='NA', max_length=100),
            preserve_default=False,
        ),
    ]
