# Generated by Django 5.0.7 on 2024-07-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'Staff'), (2, 'Student'), (3, 'Admin')], default=3, max_length=10),
        ),
    ]
