# Generated by Django 5.0.7 on 2024-07-21 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_customuser_name_alter_customuser_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffs',
            old_name='admin',
            new_name='basic_details',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='admin',
            new_name='basic_details',
        ),
    ]
